# Generated by Django 4.0.4 on 2022-06-12 03:50

from django.db import migrations, models
import django_enum_choices.choice_builders
import django_enum_choices.fields
import mainFornecedor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEmpresa', models.CharField(max_length=255, unique=True, verbose_name='Nome empresa')),
                ('EhCPFCNPJ', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], enum_class=mainFornecedor.models.EnumCPFCNPJ, max_length=4)),
                ('cnpj', models.CharField(blank=True, max_length=25, unique=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=10, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=80, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('uF', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Distrito Federal', 'Distrito Federal'), ('Espírito Santo', 'Espírito Santo'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Minas Gerais', 'Minas Gerais'), ('Pará', 'Pará'), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('Santa Catarina', 'Santa Catarina'), ('São Paulo', 'São Paulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], enum_class=mainFornecedor.models.EnumUF, max_length=19)),
                ('pessoaContato', models.CharField(max_length=50, verbose_name='Pessoa Contato')),
                ('dataHoraCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora Cadastro')),
                ('dataHoraAlteracao', models.DateTimeField(auto_now=True, verbose_name='Data e Hora Alteração')),
            ],
        ),
    ]
